### ISSUE TITLE
Not working with Redux

### ISSUE THREAD

**Issue by allroundexperts** [nachos-ui/nachos-ui#46]
Hi , None of the components of this ui are working when they are used in connect function of react-redux library.
![simulator screen shot - iphone 6 - 2018-06-20 at 03 38 42](https://user-images.githubusercontent.com/30054992/41627837-749a2ee2-743b-11e8-89d2-2ac415f38b9e.png)

Please see the image above.

**Comment by darkmantle** [comment]
I get the same error when using a Button.

Not using Redux.

**Comment by paullyFIRE** [comment]
Same error when using the library... Bare react-native project.

**Comment by mattapperson** [comment]
Sorry for the delay, for some reason I only got an alert from GitHub on that last comment (thanks @paullyFIRE lol)

I have a RN project setup as part of the testing of the project... no issues are immediately apparent. Are you all only seeing this when using a Button?

**Comment by mattapperson** [comment]
@allroundexperts would you be able to post the code from your loginform.js?

**Comment by mattapperson** [comment]
Question for all of you, do you have a theme provider setup?

**Comment by darkmantle** [comment]
@mattapperson I didn't... was using the defaults for everything.

**Comment by mattapperson** [comment]
Ah, yes the theme providor is required even when using the default theme. Perhaps I should update the docs to make that more clear, and add an error message to that effect if one is not used

**Comment by darkmantle** [comment]
@mattapperson That would help - it doesn't say it **anywhere** in the documentation - at the very least it should have the basic minimum required to work.

**Comment by chunf** [comment]
Hi @mattapperson @darkmantle, i am still relatively new to React Native, do you mind sharing some code code snippet or library that would help me to add a theme provider to my nachos-ui based project? My project was working thus far until upgrading to the latest nachos-ui.

**Comment by mattapperson** [comment]
There are docs on this, though visability that they exist is... non-existent (sorry, work was busy the past few weeks) 

https://github.com/nachos-ui/nachos-ui/blob/master/src/components/Theme/ThemeProvider.md
